// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dvarmalchus.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Dvarmalchus _$DvarmalchusFromJson(Map<String, dynamic> json) => Dvarmalchus(
      country: json['country'] as String,
      content: Content.fromJson(json['content'] as Map<String, dynamic>),
      records: Records.fromJson(json['records'] as Map<String, dynamic>),
      extras: (json['extras'] as List<dynamic>)
          .map((e) => Extra.fromJson(e as Map<String, dynamic>))
          .toList(),
      sunday_date: json['sunday_date'] as String,
      title: json['title'] as String,
    );

Map<String, dynamic> _$DvarmalchusToJson(Dvarmalchus instance) =>
    <String, dynamic>{
      'country': instance.country,
      'content': instance.content,
      'records': instance.records,
      'extras': instance.extras,
      'sunday_date': instance.sunday_date,
      'title': instance.title,
    };

Content _$ContentFromJson(Map<String, dynamic> json) => Content(
      chumash_1: json['chumash_1'] as String,
      chumash_2: json['chumash_2'] as String,
      chumash_3: json['chumash_3'] as String,
      chumash_4: json['chumash_4'] as String,
      chumash_5: json['chumash_5'] as String,
      chumash_6: json['chumash_6'] as String,
      chumash_7: json['chumash_7'] as String,
      dvarMalchus: json['dvarMalchus'] as String,
      rambam_1_1: json['rambam_1_1'] as String,
      rambam_1_2: json['rambam_1_2'] as String,
      rambam_1_3: json['rambam_1_3'] as String,
      rambam_1_4: json['rambam_1_4'] as String,
      rambam_1_5: json['rambam_1_5'] as String,
      rambam_1_6: json['rambam_1_6'] as String,
      rambam_1_7: json['rambam_1_7'] as String,
      rambam_3_1: json['rambam_3_1'] as String,
      rambam_3_2: json['rambam_3_2'] as String,
      rambam_3_3: json['rambam_3_3'] as String,
      rambam_3_4: json['rambam_3_4'] as String,
      rambam_3_5: json['rambam_3_5'] as String,
      rambam_3_6: json['rambam_3_6'] as String,
      rambam_3_7: json['rambam_3_7'] as String,
      seferm_1: json['seferm_1'] as String,
      seferm_2: json['seferm_2'] as String,
      seferm_3: json['seferm_3'] as String,
      seferm_4: json['seferm_4'] as String,
      seferm_5: json['seferm_5'] as String,
      seferm_6: json['seferm_6'] as String,
      seferm_7: json['seferm_7'] as String,
      tanya_1: json['tanya_1'] as String,
      tanya_2: json['tanya_2'] as String,
      tanya_3: json['tanya_3'] as String,
      tanya_4: json['tanya_4'] as String,
      tanya_5: json['tanya_5'] as String,
      tanya_6: json['tanya_6'] as String,
      tanya_7: json['tanya_7'] as String,
      tehilim_1: json['tehilim_1'] as String,
      tehilim_2: json['tehilim_2'] as String,
      tehilim_3: json['tehilim_3'] as String,
      tehilim_4: json['tehilim_4'] as String,
      tehilim_5: json['tehilim_5'] as String,
      tehilim_6: json['tehilim_6'] as String,
      tehilim_7: json['tehilim_7'] as String,
      yomyom_1: json['yomyom_1'] as String,
      yomyom_2: json['yomyom_2'] as String,
      yomyom_3: json['yomyom_3'] as String,
      yomyom_4: json['yomyom_4'] as String,
      yomyom_5: json['yomyom_5'] as String,
      yomyom_6: json['yomyom_6'] as String,
      yomyom_7: json['yomyom_7'] as String,
    );

Map<String, dynamic> _$ContentToJson(Content instance) => <String, dynamic>{
      'chumash_1': instance.chumash_1,
      'chumash_2': instance.chumash_2,
      'chumash_3': instance.chumash_3,
      'chumash_4': instance.chumash_4,
      'chumash_5': instance.chumash_5,
      'chumash_6': instance.chumash_6,
      'chumash_7': instance.chumash_7,
      'dvarMalchus': instance.dvarMalchus,
      'rambam_1_1': instance.rambam_1_1,
      'rambam_1_2': instance.rambam_1_2,
      'rambam_1_3': instance.rambam_1_3,
      'rambam_1_4': instance.rambam_1_4,
      'rambam_1_5': instance.rambam_1_5,
      'rambam_1_6': instance.rambam_1_6,
      'rambam_1_7': instance.rambam_1_7,
      'rambam_3_1': instance.rambam_3_1,
      'rambam_3_2': instance.rambam_3_2,
      'rambam_3_3': instance.rambam_3_3,
      'rambam_3_4': instance.rambam_3_4,
      'rambam_3_5': instance.rambam_3_5,
      'rambam_3_6': instance.rambam_3_6,
      'rambam_3_7': instance.rambam_3_7,
      'seferm_1': instance.seferm_1,
      'seferm_2': instance.seferm_2,
      'seferm_3': instance.seferm_3,
      'seferm_4': instance.seferm_4,
      'seferm_5': instance.seferm_5,
      'seferm_6': instance.seferm_6,
      'seferm_7': instance.seferm_7,
      'tanya_1': instance.tanya_1,
      'tanya_2': instance.tanya_2,
      'tanya_3': instance.tanya_3,
      'tanya_4': instance.tanya_4,
      'tanya_5': instance.tanya_5,
      'tanya_6': instance.tanya_6,
      'tanya_7': instance.tanya_7,
      'tehilim_1': instance.tehilim_1,
      'tehilim_2': instance.tehilim_2,
      'tehilim_3': instance.tehilim_3,
      'tehilim_4': instance.tehilim_4,
      'tehilim_5': instance.tehilim_5,
      'tehilim_6': instance.tehilim_6,
      'tehilim_7': instance.tehilim_7,
      'yomyom_1': instance.yomyom_1,
      'yomyom_2': instance.yomyom_2,
      'yomyom_3': instance.yomyom_3,
      'yomyom_4': instance.yomyom_4,
      'yomyom_5': instance.yomyom_5,
      'yomyom_6': instance.yomyom_6,
      'yomyom_7': instance.yomyom_7,
    };

Records _$RecordsFromJson(Map<String, dynamic> json) => Records(
      chumash_1: json['chumash_1'] as String,
      chumash_2: json['chumash_2'] as String,
      chumash_3: json['chumash_3'] as String,
      chumash_4: json['chumash_4'] as String,
      chumash_5: json['chumash_5'] as String,
      chumash_6: json['chumash_6'] as String,
      chumash_7: json['chumash_7'] as String,
      dvarMalchus: json['dvarMalchus'] as String,
      rambam_1_1: json['rambam_1_1'] as String,
      rambam_1_2: json['rambam_1_2'] as String,
      rambam_1_3: json['rambam_1_3'] as String,
      rambam_1_4: json['rambam_1_4'] as String,
      rambam_1_5: json['rambam_1_5'] as String,
      rambam_1_6: json['rambam_1_6'] as String,
      rambam_1_7: json['rambam_1_7'] as String,
      rambam_3_1: json['rambam_3_1'] as String,
      rambam_3_2: json['rambam_3_2'] as String,
      rambam_3_3: json['rambam_3_3'] as String,
      rambam_3_4: json['rambam_3_4'] as String,
      rambam_3_5: json['rambam_3_5'] as String,
      rambam_3_6: json['rambam_3_6'] as String,
      rambam_3_7: json['rambam_3_7'] as String,
      seferm_1: json['seferm_1'] as String,
      seferm_2: json['seferm_2'] as String,
      seferm_3: json['seferm_3'] as String,
      seferm_4: json['seferm_4'] as String,
      seferm_5: json['seferm_5'] as String,
      seferm_6: json['seferm_6'] as String,
      seferm_7: json['seferm_7'] as String,
      tanya_1: json['tanya_1'] as String,
      tanya_2: json['tanya_2'] as String,
      tanya_3: json['tanya_3'] as String,
      tanya_4: json['tanya_4'] as String,
      tanya_5: json['tanya_5'] as String,
      tanya_6: json['tanya_6'] as String,
      tanya_7: json['tanya_7'] as String,
      tehilim_1: json['tehilim_1'] as String,
      tehilim_2: json['tehilim_2'] as String,
      tehilim_3: json['tehilim_3'] as String,
      tehilim_4: json['tehilim_4'] as String,
      tehilim_5: json['tehilim_5'] as String,
      tehilim_6: json['tehilim_6'] as String,
      tehilim_7: json['tehilim_7'] as String,
      yomyom_1: json['yomyom_1'] as String,
      yomyom_2: json['yomyom_2'] as String,
      yomyom_3: json['yomyom_3'] as String,
      yomyom_4: json['yomyom_4'] as String,
      yomyom_5: json['yomyom_5'] as String,
      yomyom_6: json['yomyom_6'] as String,
      yomyom_7: json['yomyom_7'] as String,
    );

Map<String, dynamic> _$RecordsToJson(Records instance) => <String, dynamic>{
      'chumash_1': instance.chumash_1,
      'chumash_2': instance.chumash_2,
      'chumash_3': instance.chumash_3,
      'chumash_4': instance.chumash_4,
      'chumash_5': instance.chumash_5,
      'chumash_6': instance.chumash_6,
      'chumash_7': instance.chumash_7,
      'dvarMalchus': instance.dvarMalchus,
      'rambam_1_1': instance.rambam_1_1,
      'rambam_1_2': instance.rambam_1_2,
      'rambam_1_3': instance.rambam_1_3,
      'rambam_1_4': instance.rambam_1_4,
      'rambam_1_5': instance.rambam_1_5,
      'rambam_1_6': instance.rambam_1_6,
      'rambam_1_7': instance.rambam_1_7,
      'rambam_3_1': instance.rambam_3_1,
      'rambam_3_2': instance.rambam_3_2,
      'rambam_3_3': instance.rambam_3_3,
      'rambam_3_4': instance.rambam_3_4,
      'rambam_3_5': instance.rambam_3_5,
      'rambam_3_6': instance.rambam_3_6,
      'rambam_3_7': instance.rambam_3_7,
      'seferm_1': instance.seferm_1,
      'seferm_2': instance.seferm_2,
      'seferm_3': instance.seferm_3,
      'seferm_4': instance.seferm_4,
      'seferm_5': instance.seferm_5,
      'seferm_6': instance.seferm_6,
      'seferm_7': instance.seferm_7,
      'tanya_1': instance.tanya_1,
      'tanya_2': instance.tanya_2,
      'tanya_3': instance.tanya_3,
      'tanya_4': instance.tanya_4,
      'tanya_5': instance.tanya_5,
      'tanya_6': instance.tanya_6,
      'tanya_7': instance.tanya_7,
      'tehilim_1': instance.tehilim_1,
      'tehilim_2': instance.tehilim_2,
      'tehilim_3': instance.tehilim_3,
      'tehilim_4': instance.tehilim_4,
      'tehilim_5': instance.tehilim_5,
      'tehilim_6': instance.tehilim_6,
      'tehilim_7': instance.tehilim_7,
      'yomyom_1': instance.yomyom_1,
      'yomyom_2': instance.yomyom_2,
      'yomyom_3': instance.yomyom_3,
      'yomyom_4': instance.yomyom_4,
      'yomyom_5': instance.yomyom_5,
      'yomyom_6': instance.yomyom_6,
      'yomyom_7': instance.yomyom_7,
    };

Extra _$ExtraFromJson(Map<String, dynamic> json) => Extra(
      subject: json['subject'] as String,
      webSubject: json['webSubject'] as String,
      position: json['position'] as String,
      text_color: json['text_color'] as String,
      type: json['type'] as String,
      arr: (json['arr'] as List<dynamic>?)?.map((e) => e as String).toList(),
      url: json['url'] as String?,
    );

Map<String, dynamic> _$ExtraToJson(Extra instance) => <String, dynamic>{
      'subject': instance.subject,
      'webSubject': instance.webSubject,
      'position': instance.position,
      'text_color': instance.text_color,
      'type': instance.type,
      'arr': instance.arr,
      'url': instance.url,
    };
